### ISSUE TITLE
Compile PerfectLib error in Ubuntu 14.04

### ISSUE THREAD

**Issue by lokinfey** [PerfectlySoft/Perfect#107]
I use make to compile PerfectLib (sudo make) ,but show this error:
swift -frontend -c ICU.swift NetNamedPipe.swift File.swift Threading.swift LibEvent.swift Bytes.swift FastCGI.swift LogManager.swift NetTCPSSL.swift PerfectServer.swift WebConnection.swift Closeable.swift FastCGIServer.swift Net.swift Utilities.swift MimeReader.swift NetTCP.swift SessionManager.swift WebRequest.swift HTTPServer.swift MimeType.swift PageHandler.swift SQLite.swift WebResponse.swift Dir.swift Mustache.swift PerfectError.swift SysProcess.swift DynamicLoader.swift JSON.swift Utilities-Server.swift Routing.swift StaticFileHandler.swift WebSocketHandler.swift JSONConvertible.swift  -primary-file cURL.swift \
		-emit-module-path ./tmp/cURL.swiftmodule \
		-emit-module-doc-path ./tmp/cURL.swiftdoc \
		-emit-dependencies-path ./tmp/cURL.d \
		-emit-reference-dependencies-path ./tmp/cURL.swiftdeps \
		-g -Onone -Xcc -DDEBUG=1 -emit-module -I /usr/include/ -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -I linked/cURL_Linux -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge -g -Onone -Xcc -DDEBUG=1 -emit-module -I /usr/include/ -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -I linked/cURL_Linux -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge \
		-o cURL.o
cURL.swift:84:13: error: use of unresolved identifier 'CURLOPT_HEADERDATA'
                setOption(CURLOPT_HEADERDATA, v: opaqueMe)
                          ^~~~~~~~~~~~~~~~~~
cURL.swift:85:13: error: use of unresolved identifier 'CURLOPT_WRITEDATA'
                setOption(CURLOPT_WRITEDATA, v: opaqueMe)
                          ^~~~~~~~~~~~~~~~~
cURL.swift:86:13: error: use of unresolved identifier 'CURLOPT_READDATA'
                setOption(CURLOPT_READDATA, v: opaqueMe)
                          ^~~~~~~~~~~~~~~~
make: *** [cURL.o] Error 1

**Comment by johnmorrell** [comment]
I have hit this issue too. Introduced in:

https://github.com/PerfectlySoft/Perfect/commit/59ce3419d75aaad0cb93d75ffad80a059f0bfcc3

**Comment by amclachlan** [comment]
I'm currently running into this issue as well.
Using Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64) in VMWare.

**Comment by lokinfey** [comment]
ok i can run it now thx all

**Comment by chrismays** [comment]
How was it fixed? I'm still running into this error.

**Comment by lokinfey** [comment]
You can see my blog http://blog.csdn.net/kinfey/article/details/50664353 (Chinese only )

**Comment by stuffmc** [comment]
for @chrismays  and others: `sudo git checkout 0ef42b3`, until they fix it back on `master`‚ thanks @lokinfey (and thanks @johnmorrell for pointing the bad commit)

**Comment by solidsnack** [comment]
```diff
diff --git a/PerfectLib/cURL.swift b/PerfectLib/cURL.swift
index 8fb30e1..66f90b2 100644
--- a/PerfectLib/cURL.swift
+++ b/PerfectLib/cURL.swift
@@ -81,9 +81,9 @@ public class CURL {
        func setCurlOpts() {
                curl_easy_setopt_long(self.curl!, CURLOPT_NOSIGNAL, 1)
                let opaqueMe = UnsafeMutablePointer<Void>(Unmanaged.passUnretain
-               setOption(CURLOPT_HEADERDATA, v: opaqueMe)
-               setOption(CURLOPT_WRITEDATA, v: opaqueMe)
-               setOption(CURLOPT_READDATA, v: opaqueMe)
+               setOption(CURLOPT_WRITEHEADER, v: opaqueMe)
+               setOption(CURLOPT_FILE, v: opaqueMe)
+               setOption(CURLOPT_INFILE, v: opaqueMe)
                
                let headerReadFunc: curl_func = {
                        (a: UnsafeMutablePointer<Void>, size: Int, num: Int, p: 
```

**Comment by stuffmc** [comment]
@solidsnack is this sent as a pull request?

**Comment by solidsnack** [comment]
@stuffmc It does fix the problem but I do not think it is ideal. `CURLOPT_READDATA` is defined as an alias `CURLOPT_INFILE` in the headers. I thought maybe someone would chime in and say, a different set of `clang`/`llvm` tools would fix the issue (maybe such aliases would be loadable with these new tools, and these tools might be the default on 15.10).

If that is not the case, I will submit a pull request through the normal mechanism.

**Comment by solidsnack** [comment]
Damn, deleted it.

**Comment by solidsnack** [comment]
The diff is now here:

https://github.com/solidsnack/Perfect/commit/8776db7b05f876de5af6b80f0651431c47e66b35

The PR is #114

**Comment by ccabanero** [comment]
Hello, running into this same issue.  Here are notes on my steps if it helps you troubleshoot.  Thank you!

https://gist.github.com/ccabanero/f221d718852bfd8d0898

**Comment by kjessup** [comment]
OK, this should be fixed up now. Please confirm if you have a chance and I will close this issue.

**Comment by ccabanero** [comment]
Thanks @kjessup - confirming that I no longer see this error reported above in my previous comment.

**Comment by kjessup** [comment]
Great! We now have #if Ubuntu_14_04 and #if Ubuntu_15_10 which can be used to take care of these kinds of situations in the future.

**Comment by stuffmc** [comment]
*not* fixed for me, @kjessup — I did a `git pull origin master` and again `make`, same problem.

**Comment by ambientlight** [comment]
just switched to swift 3.0 version. 
they issue persists when attempting to build with SPM on Ubuntu_14_04 on cb20e3afb4113c11e19c581bf0f087245516f5e0

(1.0 builds fine with make)
